"""initial migration

Revision ID: 5151f4ec6575
Revises: 
Create Date: 2026-04-12 05:35:08.790026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5151f4ec6575'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('ts', sa.Integer(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('final', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'seq', name='uq_conversation_seq')
    )
    op.create_index(op.f('ix_conversation_events_conversation_id'), 'conversation_events', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_events_seq'), 'conversation_events', ['seq'], unique=False)
    op.create_index(op.f('ix_conversation_events_session_id'), 'conversation_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversation_events_ts'), 'conversation_events', ['ts'], unique=False)
    op.create_table('essay_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('ocr_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_essay_submissions_conversation_id'), 'essay_submissions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_essay_submissions_session_id'), 'essay_submissions', ['session_id'], unique=False)
    op.create_table('public_vocab_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('definition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lang', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_vocab_entries_term'), 'public_vocab_entries', ['term'], unique=True)
    op.create_table('user_vocab_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('term', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_vocab_queries_conversation_id'), 'user_vocab_queries', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_user_vocab_queries_session_id'), 'user_vocab_queries', ['session_id'], unique=False)
    op.create_index(op.f('ix_user_vocab_queries_term'), 'user_vocab_queries', ['term'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('essay_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['essay_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_essay_results_submission_id'), 'essay_results', ['submission_id'], unique=False)
    op.create_table('learning_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('milestones', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_paths_user_id'), 'learning_paths', ['user_id'], unique=False)
    op.create_table('learning_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_records_user_id'), 'learning_records', ['user_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    op.create_table('vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('definition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pronunciation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('example', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mastery_level', sa.Integer(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_user_id'), 'vocabulary', ['user_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_word'), 'vocabulary', ['word'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocabulary_word'), table_name='vocabulary')
    op.drop_index(op.f('ix_vocabulary_user_id'), table_name='vocabulary')
    op.drop_table('vocabulary')
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_learning_records_user_id'), table_name='learning_records')
    op.drop_table('learning_records')
    op.drop_index(op.f('ix_learning_paths_user_id'), table_name='learning_paths')
    op.drop_table('learning_paths')
    op.drop_index(op.f('ix_essay_results_submission_id'), table_name='essay_results')
    op.drop_table('essay_results')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_vocab_queries_term'), table_name='user_vocab_queries')
    op.drop_index(op.f('ix_user_vocab_queries_session_id'), table_name='user_vocab_queries')
    op.drop_index(op.f('ix_user_vocab_queries_conversation_id'), table_name='user_vocab_queries')
    op.drop_table('user_vocab_queries')
    op.drop_index(op.f('ix_public_vocab_entries_term'), table_name='public_vocab_entries')
    op.drop_table('public_vocab_entries')
    op.drop_index(op.f('ix_essay_submissions_session_id'), table_name='essay_submissions')
    op.drop_index(op.f('ix_essay_submissions_conversation_id'), table_name='essay_submissions')
    op.drop_table('essay_submissions')
    op.drop_index(op.f('ix_conversation_events_ts'), table_name='conversation_events')
    op.drop_index(op.f('ix_conversation_events_session_id'), table_name='conversation_events')
    op.drop_index(op.f('ix_conversation_events_seq'), table_name='conversation_events')
    op.drop_index(op.f('ix_conversation_events_conversation_id'), table_name='conversation_events')
    op.drop_table('conversation_events')
    # ### end Alembic commands ###
